INFO : 2021-03-10 22:17:19,748 : FTS.py:47 : something
INFO : 2021-03-10 22:17:19,748 : FTS.py:47 : something
INFO : 2021-03-10 22:17:19,748 : FTS.py:47 : something
DEBUG : 2021-03-10 22:17:26,714 : ReceiveConnections.py:37 : receive connection started
DEBUG : 2021-03-10 22:17:27,370 : ReceiveConnections.py:37 : receive connection started
INFO : 2021-03-10 22:17:32,172 : DataPackageServer.py:150 : sending client version info
INFO : 2021-03-10 22:17:32,177 : DataPackageServer.py:144 : sending client version json
INFO : 2021-03-10 22:17:33,029 : ReceiveConnections.py:54 : client connected
INFO : 2021-03-10 22:17:33,030 : Orchestrator.py:138 : client has connected
DEBUG : 2021-03-10 22:17:33,030 : ReceiveConnections.py:37 : receive connection started
INFO : 2021-03-10 22:17:33,030 : Orchestrator.py:138 : client has connected
INFO : 2021-03-10 22:17:33,030 : Orchestrator.py:138 : client has connected
INFO : 2021-03-10 22:17:33,136 : Orchestrator.py:161 : finished establishing connectionFAST
INFO : 2021-03-10 22:17:33,136 : Orchestrator.py:161 : finished establishing connectionFAST
INFO : 2021-03-10 22:17:33,136 : Orchestrator.py:161 : finished establishing connectionFAST
WARNING : 2021-03-10 22:17:33,141 : SendCoTAbstractController.py:40 : there has been an exception in the creation of a database instance of this object 'RawCoT' object has no attribute 'dbController'
DEBUG : 2021-03-10 22:17:33,142 : Orchestrator.py:486 : connection data from client FAST successfully processed
DEBUG : 2021-03-10 22:17:33,142 : Orchestrator.py:486 : connection data from client FAST successfully processed
DEBUG : 2021-03-10 22:17:33,142 : Orchestrator.py:486 : connection data from client FAST successfully processed
DEBUG : 2021-03-10 22:18:27,478 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:19:27,490 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:19:27,537 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:20:27,551 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:20:27,629 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:21:27,639 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:21:27,655 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:22:27,668 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:22:27,731 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:23:27,743 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:23:27,789 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:24:27,795 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:24:27,827 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:25:27,842 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:25:27,935 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:26:27,948 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:26:28,026 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:27:28,035 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:27:28,096 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:28:28,111 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:28:28,142 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:29:28,154 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:29:28,185 : ReceiveConnections.py:37 : receive connection started
INFO : 2021-03-10 22:29:35,625 : Orchestrator.py:289 : initiating client disconnection
INFO : 2021-03-10 22:29:35,625 : Orchestrator.py:289 : initiating client disconnection
INFO : 2021-03-10 22:29:35,625 : Orchestrator.py:289 : initiating client disconnection
INFO : 2021-03-10 22:29:35,627 : Orchestrator.py:306 : client disconnection has concluded FAST
INFO : 2021-03-10 22:29:35,627 : Orchestrator.py:306 : client disconnection has concluded FAST
INFO : 2021-03-10 22:29:35,627 : Orchestrator.py:306 : client disconnection has concluded FAST
WARNING : 2021-03-10 22:30:28,196 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:30:28,197 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:31:28,199 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:31:28,230 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:32:28,241 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:32:28,242 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:33:28,253 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:33:28,347 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:34:28,347 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:34:28,394 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:35:28,398 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:35:28,490 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:36:28,500 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:36:28,578 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:37:28,586 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:37:28,647 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:38:28,662 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:38:28,678 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:39:28,685 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:39:28,701 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:40:28,712 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:40:28,808 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:41:28,814 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:41:28,846 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:42:28,861 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:42:28,925 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:43:28,930 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:43:28,946 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:44:28,949 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:44:28,953 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:45:28,967 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:45:29,030 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:46:29,031 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:46:29,126 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:47:29,133 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:47:29,212 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:48:29,217 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:48:29,263 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:49:29,277 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:49:29,325 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:50:29,330 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:50:29,361 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:51:29,368 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:51:29,372 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:52:29,379 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:52:29,441 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:53:29,455 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:53:29,487 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:54:29,491 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:54:29,492 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:55:29,506 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:55:29,506 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:56:29,522 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:56:29,538 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:57:29,551 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:57:29,551 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:58:29,564 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:58:29,580 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 22:59:29,581 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 22:59:29,613 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:00:29,617 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:00:29,617 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:01:29,622 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:01:29,653 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:02:29,659 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:02:29,691 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:03:29,697 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:03:29,745 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:04:29,754 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:04:29,755 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:05:29,760 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:05:29,764 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:06:29,773 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:06:29,777 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:07:29,788 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:07:29,789 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:08:29,798 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:08:29,802 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:09:29,816 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:09:29,895 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:10:29,899 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:10:29,947 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:11:29,962 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:11:29,963 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:12:29,973 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:12:30,068 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:13:30,075 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:13:30,078 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:14:30,091 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:14:30,153 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:15:30,164 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:15:30,180 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:16:30,187 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:16:30,267 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:17:30,280 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:17:30,328 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:18:30,331 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:18:30,332 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:19:30,345 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:19:30,392 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:20:30,394 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:20:30,457 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:21:30,459 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:21:30,553 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:22:30,564 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:22:30,660 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:23:30,661 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:23:30,740 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:24:30,741 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:24:30,757 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:25:30,768 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:25:30,800 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:26:30,806 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:26:30,807 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:27:30,810 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:27:30,826 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:28:30,828 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:28:30,891 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:29:30,906 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:29:30,938 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:30:30,953 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:30:30,985 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:31:30,991 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:31:31,006 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:32:31,011 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:32:31,104 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:33:31,104 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:33:31,181 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:34:31,189 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:34:31,267 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:35:31,282 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:35:31,297 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:36:31,302 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:36:31,306 : ReceiveConnections.py:37 : receive connection started
ERROR : 2021-03-10 23:37:05,588 : TCPDataPackageService.py:31 : there has been an exception in Data Package service startup maximum recursion depth exceeded while calling a Python object
WARNING : 2021-03-10 23:37:31,321 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:37:31,352 : ReceiveConnections.py:37 : receive connection started
ERROR : 2021-03-10 23:37:59,392 : SSLDataPackageService.py:44 : there has been an exception in Data Package service startup maximum recursion depth exceeded while calling a Python object
WARNING : 2021-03-10 23:38:31,357 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:38:31,389 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:39:31,397 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:39:31,397 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:40:31,403 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:40:31,406 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:41:31,422 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:41:31,499 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:42:31,503 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:42:31,506 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:43:31,507 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:43:31,554 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:44:31,566 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:44:31,660 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:45:31,664 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:45:31,742 : ReceiveConnections.py:37 : receive connection started
WARNING : 2021-03-10 23:46:31,749 : ReceiveConnections.py:70 : error in Receive connections listen function timed out
DEBUG : 2021-03-10 23:46:31,810 : ReceiveConnections.py:37 : receive connection started
